#!/bin/sh
#
# dwm-session
# use this as the exec from /usr/share/xsessions/dwm.desktop or ...
# add `export STARTUP=dwm-session` to .xsession and use startx
#
export DISPLAY=${DISPLAY:-:0}

xhost +local: >/dev/null &

# some x options
xset b off &


# Clean up after GDM
xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
      -remove _NET_DESKTOP_NAMES \
      -remove _NET_CURRENT_DESKTOP 2> /dev/null

exec $HOME/.local/bin/dwm
